@baseURL = http://localhost:3000
@authToken = {{autentica_usuario.response.body.access_token}}

# @name nova_conta
POST {{baseURL}}/accounts
Content-Type: application/json

{
    "nome": "kevin diego",
    "email": "kevindiego@gmail.com",
    "senha": "123456"
}

###

# @name autentica_usuario
POST {{baseURL}}/sessions
Content-Type: application/json

{
    "email": "kevindiego@gmail.com",
    "senha": "123456"
}

###

# @name cria_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "titulo": "Qual melhor sistema",
    "conteudo": "Qual melhor sistema operacional para desenvolvimento web?"
}


###

# @name fetch_questions
GET {{baseURL}}/questions?page=2
Content-Type: application/json
Authorization: Bearer {{authToken}}

